export const DEFAULT_REPO_DESCRIPTION = 'Repository automatically generated by Safis CMS.'

export const BLOB = 'blob'
export const TREE = 'tree'
export const COMMIT = 'commit'

export const itemTypes = {
  BLOB,
  TREE,
  COMMIT,
}

export const fileModes = {
  [BLOB]: '100644',
  [TREE]: '040000',
  [COMMIT]: '160000',
}

export const errors = { NOT_FOUND: 'NOT_FOUND' }
